const express = require("express");
const { auth } = require("../middlewares/auth");
const { nearByPeopleByLocation, bestMatchForYou, searchBestMatch, getProfileData } = require("../controllers/User");
const { cachingBestMatch, cachingSearchMatch } = require("../middlewares/cacheMiddleware");
const router = express.Router();
router.get("/get-near-user",auth,nearByPeopleByLocation);
router.get("/best-match", auth,  bestMatchForYou);
router.get("/search-match",auth, searchBestMatch);
router.get("/get-user/:userId",auth,getProfileData);
module.exports = router;